# Generated by Django 3.2.5 on 2022-07-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_price', models.IntegerField()),
                ('imtem_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
