# Generated by Django 3.2.5 on 2022-08-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220816_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='item_datetime',
            field=models.DateTimeField(auto_now_add=True, max_length=64),
        ),
    ]
