# Generated by Django 4.2.3 on 2023-07-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddings',
            name='item_has_bid',
        ),
        migrations.AddField(
            model_name='listings',
            name='listing_has_bid',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
