# Generated by Django 3.2.5 on 2022-07-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220727_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='item_listed_timestamp',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_created_timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_created_timestamp',
        ),
    ]
