# Generated by Django 4.2.3 on 2023-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_biddings_item_has_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='listing_has_bid',
        ),
        migrations.AddField(
            model_name='user',
            name='saved_to_watchlist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
