# Generated by Django 4.2.3 on 2023-07-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_rename_biddings_bidding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='saved_to_watchlist',
            new_name='any_listings_saved_to_watchlist',
        ),
    ]
