# Generated by Django 4.2.3 on 2023-07-29 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_saved_to_watchlist_user_any_listings_saved_to_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_watchlisters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
