# Generated by Django 4.2.3 on 2023-07-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_listing_watchlisters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_watchlisters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='any_listings_saved_to_watchlist',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_listings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing')),
            ],
        ),
    ]
