# Generated by Django 4.2.3 on 2023-07-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listing_listing_watchlisters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.IntegerField(),
        ),
    ]
