# Generated by Django 4.2.3 on 2023-07-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_listing_price_alter_bidding_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(default='vehicle', max_length=200),
            preserve_default=False,
        ),
    ]
