# Generated by Django 4.2.3 on 2023-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_comment_text_comment_new_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_image_url',
            field=models.URLField(default='//upload.wikimedia.org/wikipedia/commons/thumb/6/68/Orange_tabby_cat_sitting_on_fallen_leaves-Hisashi-01A.jpg/112px-Orange_tabby_cat_sitting_on_fallen_leaves-Hisashi-01A.jpg'),
            preserve_default=False,
        ),
    ]
