# Generated by Django 4.2.3 on 2023-07-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
