# Generated by Django 4.2.3 on 2023-07-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist_listings',
            new_name='listings',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='added_to_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
