# Generated by Django 4.2.3 on 2023-07-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_rename_listings_watchlist_possible_listings_to_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing_items_added_to_watchlist',
            field=models.ManyToManyField(related_name='watchlist_users', to='auctions.listing'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
