# Generated by Django 4.2.3 on 2023-07-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_created_at_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_comment_text',
            field=models.TextField(max_length=1000),
        ),
    ]
