# Generated by Django 4.2.3 on 2023-07-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_comment_new_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listings',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
