# Generated by Django 4.2.3 on 2023-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_remove_user_listing_items_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='new_bid',
            field=models.IntegerField(null=True),
        ),
    ]
