# Generated by Django 4.2.3 on 2023-07-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_rename_user_bidding_bid_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='bid_replaced_price',
            field=models.BooleanField(default=False),
        ),
    ]
