# Generated by Django 4.2.3 on 2023-07-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_bidding_bid_replaced_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding',
            name='bid_replaced_price',
        ),
    ]
