# Generated by Django 4.2.3 on 2023-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_listing_listing_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_closed',
        ),
        migrations.AddField(
            model_name='user',
            name='listing_closed',
            field=models.ManyToManyField(related_name='closed_listing', to='auctions.listing'),
        ),
    ]
