# Generated by Django 4.2.3 on 2023-07-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_remove_listing_listing_closed_user_listing_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing_closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_closed',
            field=models.BooleanField(default=False),
        ),
    ]
