# Generated by Django 4.2.3 on 2023-07-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_listing_listing_bid_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_closed',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_active',
            field=models.BooleanField(default=True),
        ),
    ]
