# Generated by Django 3.2.5 on 2022-08-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=64)),
                ('item_description', models.CharField(max_length=6400)),
                ('item_start_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_image_url', models.URLField()),
                ('item_category', models.CharField(max_length=200)),
                ('item_username', models.CharField(max_length=64)),
                ('item_datetime', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
