# Generated by Django 3.2.5 on 2022-08-18 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20220818_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
