# Generated by Django 3.2.5 on 2022-09-12 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_comment_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
